# Generate mobile test-data deploy MSBuild project from CryptoLib.Tests/Data.
# Usage:
#   .\sync-mobile-testdata.ps1
#   .\sync-mobile-testdata.ps1 -DeployProjName CryptoLib.Tests.Mobile.TestData.deployproj -AppDeployFolderName CryptoLib.Tests.Mobile
#   .\sync-mobile-testdata.ps1 -DeployProjName Project1.TestData.deployproj -AppDeployFolderName Project1
# Re-run when files under CryptoLib.Tests/Data change (or AppDeployFolderName changes), then rebuild the mobile test host.

param(
    [string]$RepoRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path,
    [string]$DeployProjName = "CryptoLib.Tests.Mobile.TestData.deployproj",
    [string]$AppDeployFolderName = "CryptoLib.Tests.Mobile"
)

$DelphiTestsDir = Join-Path $RepoRoot "CryptoLib.Tests\Delphi.Tests"
$DataDir = Join-Path $RepoRoot "CryptoLib.Tests\Data"
$OutPath = Join-Path $DelphiTestsDir $DeployProjName

if (-not (Test-Path $DataDir)) {
    Write-Error "Data directory not found: $DataDir"
    exit 1
}

function Escape-Xml([string]$Text) {
    return $Text.Replace('&', '&amp;').Replace('<', '&lt;').Replace('>', '&gt;')
}

function New-DeployFileBlock {
    param(
        [string]$IncludePath,
        [string]$RemoteDir,
        [string]$RemoteName
    )
    $inc = Escape-Xml $IncludePath
    $dir = Escape-Xml $RemoteDir
    $name = Escape-Xml $RemoteName
    return @"
        <DeployFile Include="$inc">
            <RemoteDir>$dir</RemoteDir>
            <RemoteName>$name</RemoteName>
            <DeployClass>File</DeployClass>
            <Operation>0</Operation>
            <LocalCommand/>
            <RemoteCommand/>
            <Overwrite>True</Overwrite>
        </DeployFile>
"@
}

$AndroidBlocks = New-Object System.Collections.Generic.List[string]
$IosBlocks = New-Object System.Collections.Generic.List[string]

Get-ChildItem -Path $DataDir -Recurse -File | ForEach-Object {
    $rel = $_.FullName.Substring($DataDir.Length).TrimStart('\', '/')
    $relDir = Split-Path $rel -Parent
    $fileName = Split-Path $rel -Leaf
    $include = "..\Data\$rel" -replace '/', '\'

    if ($relDir) {
        $relDirSlash = $relDir -replace '\\', '\'
        $androidRemoteDir = "$AppDeployFolderName\assets\internal\CryptoLib.Tests\Data\$relDirSlash\"
        $iosRemoteDir = "StartUpDocuments\CryptoLib.Tests\Data\$relDirSlash\"
    }
    else {
        $androidRemoteDir = "$AppDeployFolderName\assets\internal\CryptoLib.Tests\Data\"
        $iosRemoteDir = "StartUpDocuments\CryptoLib.Tests\Data\"
    }

    $AndroidBlocks.Add((New-DeployFileBlock -IncludePath $include -RemoteDir $androidRemoteDir -RemoteName $fileName))
    $IosBlocks.Add((New-DeployFileBlock -IncludePath $include -RemoteDir $iosRemoteDir -RemoteName $fileName))
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">')
[void]$sb.AppendLine('    <!-- Generated by scripts/maintenance/sync-mobile-testdata.ps1 - do not edit by hand -->')
[void]$sb.AppendLine("    <!-- AppDeployFolderName=$AppDeployFolderName DeployProjName=$DeployProjName -->")
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''Android64''">')
foreach ($b in $AndroidBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''iOSDevice64''">')
foreach ($b in $IosBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('    <ItemGroup Condition="''$(Platform)''==''iOSSimARM64''">')
foreach ($b in $IosBlocks) { [void]$sb.AppendLine($b) }
[void]$sb.AppendLine('    </ItemGroup>')
[void]$sb.AppendLine('</Project>')

$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($OutPath, $sb.ToString(), $utf8NoBom)
Write-Host "Wrote $($AndroidBlocks.Count) data deploy entries to $OutPath (AppDeployFolderName=$AppDeployFolderName)"
