{ This file was automatically created by Lazarus. Do not edit!
  This source is only used to compile and install the package.
 }

unit CryptoLib4PascalPackage;

{$warn 5023 off : no warning about unused units}
interface

uses
  ClpOidTokenizer, ClpCryptoProObjectIdentifiers, ClpECGost3410NamedCurves, 
  ClpNistObjectIdentifiers, ClpOiwObjectIdentifiers, ClpPkcsObjectIdentifiers, 
  ClpRosstandartObjectIdentifiers, ClpSecNamedCurves, ClpSecObjectIdentifiers, 
  ClpTeleTrusTObjectIdentifiers, ClpECNamedCurveTable, ClpX9ECParameters, 
  ClpX9ECParametersHolder, ClpX9ObjectIdentifiers, ClpAsymmetricCipherKeyPair, 
  ClpAsymmetricKeyParameter, ClpKeyGenerationParameters, 
  ClpECKeyPairGenerator, ClpECDomainParameters, ClpECKeyGenerationParameters, 
  ClpECKeyParameters, ClpECPrivateKeyParameters, ClpECPublicKeyParameters, 
  ClpParametersWithRandom, ClpCryptoApiRandomGenerator, 
  ClpDigestRandomGenerator, ClpDsaDigestSigner, ClpECDsaSigner, 
  ClpRandomDsaKCalculator, ClpIAsymmetricCipherKeyPair, 
  ClpIAsymmetricCipherKeyPairGenerator, ClpIAsymmetricKeyParameter, 
  ClpICipherParameters, ClpICryptoApiRandomGenerator, 
  ClpIDigestRandomGenerator, ClpIDsa, ClpIDsaDigestSigner, ClpIDsaKCalculator, 
  ClpIECDomainParameters, ClpIECDsaSigner, ClpIECKeyGenerationParameters, 
  ClpIECKeyPairGenerator, ClpIECKeyParameters, ClpIECPrivateKeyParameters, 
  ClpIECPublicKeyParameters, ClpIExtensionField, ClpIFiniteField, 
  ClpIFixedPointPreCompInfo, ClpIGenericPolynomialExtensionField, 
  ClpIGF2Polynomial, ClpIGlvEndomorphism, ClpIGlvTypeBEndomorphism, 
  ClpIGlvTypeBParameters, ClpIKeyGenerationParameters, ClpIOidTokenizer, 
  ClpIParametersWithRandom, ClpIPolynomial, ClpIPolynomialExtensionField, 
  ClpIPreCompInfo, ClpIPrimeField, ClpIRandom, ClpIRandomDsaKCalculator, 
  ClpIRandomGenerator, ClpIRandomNumberGenerator, ClpIScaleXPointMap, 
  ClpISecureRandom, ClpISigner, ClpIWNafPreCompInfo, ClpIWTauNafPreCompInfo, 
  ClpIX9ECParameters, ClpIX9ECParametersHolder, ClpIZTauElement, 
  ClpBigInteger, ClpECAlgorithms, ClpLongArray, ClpScaleXPointMap, 
  ClpSimpleBigDecimal, ClpTnaf, ClpZTauElement, ClpGlvTypeBEndomorphism, 
  ClpGlvTypeBParameters, ClpFixedPointPreCompInfo, ClpWNafPreCompInfo, 
  ClpWTauNafPreCompInfo, ClpFiniteFields, ClpGenericPolynomialExtensionField, 
  ClpGF2Polynomial, ClpPrimeField, ClpMod, ClpNat, ClpDigestUtilities, 
  ClpRandom, ClpSecureRandom, ClpSignerUtilities, ClpArrayUtils, 
  ClpBigIntegers, ClpBitConverter, ClpBits, ClpConverters, ClpCryptoLibTypes, 
  ClpTimes, ClpOSRandom, ClpRandomNumberGenerator, ClpSetWeakRef, 
  ClpParameterUtilities, ClpGeneratorUtilities, ClpCipherUtilities, 
  ClpIAesEngine, ClpIParametersWithIV, ClpIPaddedBufferedBlockCipher, 
  ClpIKeyParameter, ClpIBufferedCipherBase, ClpIBufferedCipher, 
  ClpIBufferedBlockCipher, ClpIBlockCipherPadding, ClpIBlockCipher, 
  ClpPaddedBufferedBlockCipher, ClpParametersWithIV, ClpKeyParameter, 
  ClpBufferedBlockCipher, ClpBufferedCipherBase, ClpCheck, ClpAesEngine, 
  ClpPascalCoinECIESKdfBytesGenerator, ClpPascalCoinIESEngine, 
  ClpBaseKdfBytesGenerator, ClpIESEngine, ClpECIESPublicKeyParser, 
  ClpIESCipher, ClpECDHBasicAgreement, ClpEphemeralKeyPair, ClpKeyEncoder, 
  ClpIESWithCipherParameters, ClpIESParameters, ClpEphemeralKeyPairGenerator, 
  ClpKdf2BytesGenerator, ClpIso18033KdfParameters, ClpKdfParameters, 
  ClpIIESWithCipherParameters, ClpIIESParameters, 
  ClpIPascalCoinECIESKdfBytesGenerator, ClpIPascalCoinIESEngine, 
  ClpIIESEngine, ClpIIESCipher, ClpIECIESPublicKeyParser, 
  ClpIEphemeralKeyPairGenerator, ClpIEphemeralKeyPair, ClpIKeyParser, 
  ClpIKdf2BytesGenerator, ClpIBaseKdfBytesGenerator, 
  ClpIIso18033KdfParameters, ClpIKdfParameters, ClpIDerivationFunction, 
  ClpIDerivationParameters, ClpIECDHBasicAgreement, ClpIBasicAgreement, 
  ClpCipherKeyGenerator, ClpStringUtils, ClpICipherKeyGenerator, ClpIDigest, 
  ClpIStreamCipher, ClpPkcs5S2ParametersGenerator, 
  ClpIPkcs5S2ParametersGenerator, ClpIPbeParametersGenerator, 
  ClpPbeParametersGenerator, ClpHMac, ClpMiscObjectIdentifiers, 
  ClpIanaObjectIdentifiers, ClpMacUtilities, ClpIMac, ClpIHMac, ClpDsaSigner, 
  ClpDsaKeyPairGenerator, ClpECNRSigner, ClpDsaKeyGenerationParameters, 
  ClpDsaPrivateKeyParameters, ClpDsaPublicKeyParameters, 
  ClpDsaValidationParameters, ClpDsaParameters, ClpDsaKeyParameters, 
  ClpIECNRSigner, ClpIDsaSigner, ClpIDsaKeyPairGenerator, 
  ClpIDsaPrivateKeyParameters, ClpIDsaKeyGenerationParameters, 
  ClpIDsaKeyParameters, ClpIDsaPublicKeyParameters, ClpIDsaParameters, 
  ClpIDsaValidationParameters, ClpDigest, ClpECDHCBasicAgreement, 
  ClpIECDHCBasicAgreement, ClpHMacDsaKCalculator, ClpIHMacDsaKCalculator, 
  ClpHkdfBytesGenerator, ClpIHkdfBytesGenerator, ClpHkdfParameters, 
  ClpIHkdfParameters, ClpDsaParameterGenerationParameters, 
  ClpIDsaParameterGenerationParameters, ClpDsaParametersGenerator, 
  ClpDsaParameter, ClpIDsaParameter, ClpIKeyEncoder, 
  ClpIDsaParametersGenerator, ClpIPreCompCallBack, ClpNistNamedCurves, 
  ClpNat256, ClpNat320, ClpAesLightEngine, ClpIAesLightEngine, 
  ClpCustomNamedCurves, ClpNat384, ClpNat192, ClpNat512, ClpInterleave, 
  ClpBsiObjectIdentifiers, ClpEacObjectIdentifiers, ClpIDsaExt, 
  ClpISchnorrDigestSigner, ClpIECSchnorrSipaSigner, ClpECSchnorrSipaSigner, 
  ClpSchnorrDigestSigner, ClpISchnorr, ClpISchnorrExt, ClpBlowfishEngine, 
  ClpIBlowfishEngine, ClpECC, ClpAsn1Objects, ClpSignersEncodings, 
  ClpISignersEncodings, ClpEncoders, ClpSecT283Custom, ClpSecP521R1Custom, 
  ClpSecP384R1Custom, ClpSecP256R1Custom, ClpSecP256K1Custom, ClpIX9ECC, 
  ClpX9ECC, ClpIAsn1Objects, ClpBlockCipherModes, ClpECCurveConstants, 
  ClpIBlockCipherModes, ClpIPaddingModes, ClpISecP256K1Custom, 
  ClpISecP256R1Custom, ClpISecP384R1Custom, ClpISecP521R1Custom, 
  ClpISecT283Custom, ClpPaddingModes, ClpIECC, ClpISpeckEngine, 
  ClpSpeckEngine, ClpIBufferedStreamCipher, ClpIChaChaEngine, 
  ClpIXSalsa20Engine, ClpISalsa20Engine, ClpBufferedStreamCipher, 
  ClpSalsa20Engine, ClpXSalsa20Engine, ClpChaChaEngine, ClpIRijndaelEngine, 
  ClpRijndaelEngine, ClpIIESParameterSpec, ClpIAlgorithmParameterSpec, 
  ClpIESParameterSpec, ClpCurve25519Custom, ClpICurve25519Custom, 
  ClpSpeckLegacyEngine, ClpISpeckLegacyEngine, ClpIEd25519, ClpX25519Field, 
  ClpEd25519, ClpX25519, ClpEdECObjectIdentifiers, ClpIEd25519PhSigner, 
  ClpIEd25519CtxSigner, ClpIEd25519Signer, ClpIEd25519KeyGenerationParameters, 
  ClpIX25519KeyGenerationParameters, ClpIEd25519KeyPairGenerator, 
  ClpIX25519KeyPairGenerator, ClpIEd25519PrivateKeyParameters, 
  ClpIEd25519PublicKeyParameters, ClpIX25519PublicKeyParameters, 
  ClpIX25519PrivateKeyParameters, ClpIX25519Agreement, ClpIRawAgreement, 
  ClpX25519Agreement, ClpEd25519KeyGenerationParameters, 
  ClpX25519KeyGenerationParameters, ClpEd25519PublicKeyParameters, 
  ClpEd25519PrivateKeyParameters, ClpX25519PublicKeyParameters, 
  ClpX25519PrivateKeyParameters, ClpEd25519KeyPairGenerator, 
  ClpX25519KeyPairGenerator, ClpEd25519PhSigner, ClpEd25519Signer, 
  ClpEd25519CtxSigner, ClpTeleTrusTNamedCurves, ClpAgreementUtilities, 
  ClpIKdf1BytesGenerator, ClpKdf1BytesGenerator, 
  ClpIArgon2ParametersGenerator, ClpArgon2ParametersGenerator, 
  ClpIScryptParametersGenerator, ClpScryptParametersGenerator, 
  ClpIDHAgreement, ClpIDHBasicAgreement, ClpIDHBasicKeyPairGenerator, 
  ClpIDHKeyPairGenerator, ClpIDHPrivateKeyParameters, 
  ClpIDHPublicKeyParameters, ClpIDHParametersGenerator, 
  ClpIDHKeyGenerationParameters, ClpIDHParameters, ClpIDHKeyGeneratorHelper, 
  ClpIDHKeyParameters, ClpIDHValidationParameters, ClpIDHDomainParameters, 
  ClpIDHValidationParams, ClpDHAgreement, ClpDHBasicAgreement, 
  ClpDHBasicKeyPairGenerator, ClpDHKeyPairGenerator, ClpDHParametersGenerator, 
  ClpDHKeyGeneratorHelper, ClpDHParametersHelper, ClpDHPrivateKeyParameters, 
  ClpDHPublicKeyParameters, ClpDHKeyGenerationParameters, ClpDHKeyParameters, 
  ClpDHValidationParameters, ClpDHParameters, ClpDHDomainParameters, 
  ClpDHValidationParams, ClpAESPRNGRandom, ClpCryptLibObjectIdentifiers, 
  ClpIEndoPreCompInfo, ClpEndoPreCompInfo, ClpScaleXNegateYPointMap, 
  ClpScaleYNegateXPointMap, ClpGlvTypeAEndomorphism, ClpGlvTypeAParameters, 
  ClpScalarSplitParameters, ClpIGlvTypeAParameters, ClpIGlvTypeAEndomorphism, 
  ClpIScaleXNegateYPointMap, ClpIScaleYNegateXPointMap, 
  ClpIScalarSplitParameters, ClpECCompUtilities, ClpValidityPreCompInfo, 
  ClpIValidityPreCompInfo, ClpKMac, ClpIKMac, ClpMultipliers;

implementation

end.
