{ This file was automatically created by Lazarus. Do not edit!
  This source is only used to compile and install the package.
 }

unit CryptoLib4PascalPackage;

{$warn 5023 off : no warning about unused units}
interface

uses
  ClpAsn1Encodable, ClpAsn1EncodableVector, ClpAsn1Generator, 
  ClpAsn1InputStream, ClpAsn1Null, ClpAsn1Object, ClpAsn1OctetString, 
  ClpAsn1OutputStream, ClpAsn1Sequence, ClpAsn1Set, ClpAsn1StreamParser, 
  ClpAsn1TaggedObject, ClpAsn1Tags, ClpBerApplicationSpecific, 
  ClpBerApplicationSpecificParser, ClpBerBitString, ClpBerGenerator, 
  ClpBerNull, ClpBerOctetString, ClpBerOctetStringParser, ClpBerOutputStream, 
  ClpBerSequence, ClpBerSequenceGenerator, ClpBerSequenceParser, ClpBerSet, 
  ClpBerSetParser, ClpBerTaggedObject, ClpBerTaggedObjectParser, 
  ClpConstructedOctetStream, ClpDerApplicationSpecific, ClpDerBitString, 
  ClpDerBmpString, ClpDerBoolean, ClpDerEnumerated, ClpDerExternal, 
  ClpDerExternalParser, ClpDerGeneralString, ClpDerGenerator, 
  ClpDerGraphicString, ClpDerIA5String, ClpDerInteger, ClpDerNull, 
  ClpDerNumericString, ClpDerObjectIdentifier, ClpDerOctetString, 
  ClpDerOctetStringParser, ClpDerOutputStream, ClpDerPrintableString, 
  ClpDerSequence, ClpDerSequenceGenerator, ClpDerSequenceParser, ClpDerSet, 
  ClpDerSetParser, ClpDerStringBase, ClpDerT61String, ClpDerTaggedObject, 
  ClpDerUniversalString, ClpDerUtf8String, ClpDerVideotexString, 
  ClpDerVisibleString, ClpIndefiniteLengthInputStream, ClpLimitedInputStream, 
  ClpOidTokenizer, ClpCryptoProObjectIdentifiers, ClpECGost3410NamedCurves, 
  ClpNistObjectIdentifiers, ClpOiwObjectIdentifiers, ClpPkcsObjectIdentifiers, 
  ClpRosstandartObjectIdentifiers, ClpSecNamedCurves, ClpSecObjectIdentifiers, 
  ClpTeleTrusTObjectIdentifiers, ClpECNamedCurveTable, ClpX9Curve, 
  ClpX9ECParameters, ClpX9ECParametersHolder, ClpX9ECPoint, ClpX9FieldElement, 
  ClpX9FieldID, ClpX9IntegerConverter, ClpX9ObjectIdentifiers, 
  ClpAsymmetricCipherKeyPair, ClpAsymmetricKeyParameter, 
  ClpKeyGenerationParameters, ClpECKeyPairGenerator, ClpECDomainParameters, 
  ClpECKeyGenerationParameters, ClpECKeyParameters, ClpECPrivateKeyParameters, 
  ClpECPublicKeyParameters, ClpParametersWithRandom, 
  ClpCryptoApiRandomGenerator, ClpDigestRandomGenerator, ClpDsaDigestSigner, 
  ClpECDsaSigner, ClpRandomDsaKCalculator, ClpIAbstractECMultiplier, 
  ClpIAsn1ApplicationSpecificParser, ClpIAsn1Choice, ClpIAsn1EncodableVector, 
  ClpIAsn1Generator, ClpIAsn1Null, ClpIAsn1OctetString, 
  ClpIAsn1OctetStringParser, ClpIAsn1Sequence, ClpIAsn1SequenceParser, 
  ClpIAsn1Set, ClpIAsn1SetParser, ClpIAsn1StreamParser, ClpIAsn1String, 
  ClpIAsn1TaggedObject, ClpIAsn1TaggedObjectParser, 
  ClpIAsymmetricCipherKeyPair, ClpIAsymmetricCipherKeyPairGenerator, 
  ClpIAsymmetricKeyParameter, ClpIBerApplicationSpecific, 
  ClpIBerApplicationSpecificParser, ClpIBerBitString, ClpIBerGenerator, 
  ClpIBerNull, ClpIBerOctetString, ClpIBerOctetStringParser, ClpIBerSequence, 
  ClpIBerSequenceGenerator, ClpIBerSequenceParser, ClpIBerSet, 
  ClpIBerSetParser, ClpIBerTaggedObject, ClpIBerTaggedObjectParser, 
  ClpICipherParameters, ClpICryptoApiRandomGenerator, 
  ClpIDerApplicationSpecific, ClpIDerBitString, ClpIDerBmpString, 
  ClpIDerBoolean, ClpIDerEnumerated, ClpIDerExternal, ClpIDerExternalParser, 
  ClpIDerGeneralString, ClpIDerGenerator, ClpIDerGraphicString, 
  ClpIDerIA5String, ClpIDerInteger, ClpIDerNull, ClpIDerNumericString, 
  ClpIDerObjectIdentifier, ClpIDerOctetString, ClpIDerOctetStringParser, 
  ClpIDerPrintableString, ClpIDerSequence, ClpIDerSequenceGenerator, 
  ClpIDerSequenceParser, ClpIDerSet, ClpIDerSetParser, ClpIDerStringBase, 
  ClpIDerT61String, ClpIDerTaggedObject, ClpIDerUniversalString, 
  ClpIDerUtf8String, ClpIDerVideotexString, ClpIDerVisibleString, 
  ClpIDigestRandomGenerator, ClpIDsa, ClpIDsaDigestSigner, ClpIDsaKCalculator, 
  ClpIECDomainParameters, ClpIECDsaSigner, ClpIECFieldElement, 
  ClpIECInterface, ClpIECKeyGenerationParameters, ClpIECKeyPairGenerator, 
  ClpIECKeyParameters, ClpIECPrivateKeyParameters, ClpIECPublicKeyParameters, 
  ClpIExtensionField, ClpIFilterStream, ClpIFiniteField, 
  ClpIFixedPointCombMultiplier, ClpIFixedPointPreCompInfo, 
  ClpIGenericPolynomialExtensionField, ClpIGF2Polynomial, ClpIGlvEndomorphism, 
  ClpIGlvMultiplier, ClpIGlvTypeBEndomorphism, ClpIGlvTypeBParameters, 
  ClpIKeyGenerationParameters, ClpIOidTokenizer, ClpIOSRandomNumberGenerator, 
  ClpIParametersWithRandom, ClpIPCGRandomNumberGenerator, ClpIPolynomial, 
  ClpIPolynomialExtensionField, ClpIPreCompInfo, ClpIPrimeField, 
  ClpIProxiedInterface, ClpIRandom, ClpIRandomDsaKCalculator, 
  ClpIRandomGenerator, ClpIRandomNumberGenerator, ClpIScaleXPointMap, 
  ClpISecureRandom, ClpISigner, ClpIWNafL2RMultiplier, ClpIWNafPreCompInfo, 
  ClpIWTauNafMultiplier, ClpIWTauNafPreCompInfo, ClpIX9Curve, 
  ClpIX9ECParameters, ClpIX9ECParametersHolder, ClpIX9ECPoint, 
  ClpIX9FieldElement, ClpIX9FieldID, ClpIZTauElement, ClpBigInteger, 
  ClpNumberStyles, ClpECAlgorithms, ClpECCurve, ClpECFieldElement, ClpECPoint, 
  ClpLongArray, ClpScaleXPointMap, ClpSimpleBigDecimal, ClpTnaf, 
  ClpZTauElement, ClpGlvTypeBEndomorphism, ClpGlvTypeBParameters, 
  ClpAbstractECMultiplier, ClpFixedPointCombMultiplier, 
  ClpFixedPointPreCompInfo, ClpFixedPointUtilities, ClpGlvMultiplier, 
  ClpWNafL2RMultiplier, ClpWNafPreCompInfo, ClpWNafUtilities, 
  ClpWTauNafMultiplier, ClpWTauNafPreCompInfo, ClpFiniteFields, 
  ClpGenericPolynomialExtensionField, ClpGF2Polynomial, ClpPrimeField, ClpMod, 
  ClpNat, ClpDigestUtilities, ClpRandom, ClpSecureRandom, ClpSignerUtilities, 
  ClpArrayUtils, ClpBigIntegers, ClpBitConverter, ClpBits, ClpConverters, 
  ClpCryptoLibTypes, ClpStreamSorter, ClpTimes, ClpCollectionUtilities, 
  ClpBase64, ClpHex, ClpStreamHelper, ClpBaseInputStream, ClpFilterStream, 
  ClpStreams, ClpOSRandom, ClpPcgRandomMinimal, ClpOSRandomNumberGenerator, 
  ClpPCGRandomNumberGenerator, ClpRandomNumberGenerator, ClpSetWeakRef, 
  ClpDefiniteLengthInputStream, ClpParameterUtilities, ClpGeneratorUtilities, 
  ClpCipherUtilities, ClpIAesEngine, ClpIPkcs7Padding, ClpIParametersWithIV, 
  ClpIPaddedBufferedBlockCipher, ClpIKeyParameter, ClpICbcBlockCipher, 
  ClpIBufferedCipherBase, ClpIBufferedCipher, ClpIBufferedBlockCipher, 
  ClpIBlockCipherPadding, ClpIBlockCipher, ClpCbcBlockCipher, 
  ClpPaddedBufferedBlockCipher, ClpPkcs7Padding, ClpParametersWithIV, 
  ClpKeyParameter, ClpBufferedBlockCipher, ClpBufferedCipherBase, ClpCheck, 
  ClpAesEngine, ClpPascalCoinECIESKdfBytesGenerator, ClpPascalCoinIESEngine, 
  ClpBaseKdfBytesGenerator, ClpIESEngine, ClpECIESPublicKeyParser, 
  ClpIESCipher, ClpECDHBasicAgreement, ClpEphemeralKeyPair, ClpKeyEncoder, 
  ClpZeroBytePadding, ClpIESWithCipherParameters, ClpIESParameters, 
  ClpEphemeralKeyPairGenerator, ClpKdf2BytesGenerator, 
  ClpIso18033KdfParameters, ClpKdfParameters, ClpIIESWithCipherParameters, 
  ClpIIESParameters, ClpIPascalCoinECIESKdfBytesGenerator, 
  ClpIPascalCoinIESEngine, ClpIIESEngine, ClpIIESCipher, ClpIZeroBytePadding, 
  ClpIECIESPublicKeyParser, ClpIEphemeralKeyPairGenerator, 
  ClpIEphemeralKeyPair, ClpIKeyParser, ClpIKdf2BytesGenerator, 
  ClpIBaseKdfBytesGenerator, ClpIIso18033KdfParameters, ClpIKdfParameters, 
  ClpIDerivationFunction, ClpIDerivationParameters, ClpIECDHBasicAgreement, 
  ClpIBasicAgreement, ClpSicBlockCipher, ClpCfbBlockCipher, 
  ClpCipherKeyGenerator, ClpStringUtils, ClpICipherKeyGenerator, ClpIDigest, 
  ClpISicBlockCipher, ClpIStreamCipher, ClpOfbBlockCipher, ClpIOfbBlockCipher, 
  ClpICfbBlockCipher, ClpX923Padding, ClpIX923Padding, ClpTTBCPadding, 
  ClpISO7816d4Padding, ClpITBCPadding, ClpIISO7816d4Padding, 
  ClpISO10126d2Padding, ClpIISO10126d2Padding, ClpPkcs5S2ParametersGenerator, 
  ClpIPkcs5S2ParametersGenerator, ClpIPbeParametersGenerator, 
  ClpPbeParametersGenerator, ClpHMac, ClpMiscObjectIdentifiers, 
  ClpIanaObjectIdentifiers, ClpMacUtilities, ClpIMac, ClpIHMac, ClpDsaSigner, 
  ClpDsaKeyPairGenerator, ClpECNRSigner, ClpDsaKeyGenerationParameters, 
  ClpDsaPrivateKeyParameters, ClpDsaPublicKeyParameters, 
  ClpDsaValidationParameters, ClpDsaParameters, ClpDsaKeyParameters, 
  ClpIECNRSigner, ClpIDsaSigner, ClpIDsaKeyPairGenerator, 
  ClpIDsaPrivateKeyParameters, ClpIDsaKeyGenerationParameters, 
  ClpIDsaKeyParameters, ClpIDsaPublicKeyParameters, ClpIDsaParameters, 
  ClpIDsaValidationParameters, ClpBase58, ClpDigest, ClpECDHCBasicAgreement, 
  ClpIECDHCBasicAgreement, ClpHMacDsaKCalculator, ClpIHMacDsaKCalculator, 
  ClpHkdfBytesGenerator, ClpIHkdfBytesGenerator, ClpHkdfParameters, 
  ClpIHkdfParameters, ClpDsaParameterGenerationParameters, 
  ClpIDsaParameterGenerationParameters, ClpValidityPrecompInfo, 
  ClpIValidityPrecompInfo, ClpDsaParametersGenerator, ClpDsaParameter, 
  ClpIDsaParameter, ClpIKeyEncoder, ClpIDsaParametersGenerator, 
  ClpIPreCompCallBack, ClpNistNamedCurves, ClpNat256, ClpNat320, 
  ClpAesLightEngine, ClpIAesLightEngine, ClpCustomNamedCurves, 
  ClpSecP256K1Field, ClpSecP256K1FieldElement, ClpISecP256K1FieldElement, 
  ClpSecP256K1Point, ClpISecP256K1Point, ClpSecP256K1Curve, 
  ClpISecP256K1Curve, ClpSecP384R1Field, ClpNat384, ClpSecP384R1FieldElement, 
  ClpISecP384R1FieldElement, ClpSecP384R1Point, ClpISecP384R1Point, 
  ClpSecP384R1Curve, ClpNat192, ClpISecP384R1Curve, ClpSecP521R1Field, 
  ClpNat512, ClpSecP521R1FieldElement, ClpISecP521R1FieldElement, 
  ClpSecP521R1Point, ClpISecP521R1Point, ClpSecP521R1Curve, 
  ClpISecP521R1Curve, ClpInterleave, ClpSecT283Field, ClpSecT283FieldElement, 
  ClpISecT283FieldElement, ClpSecT283K1Point, ClpISecT283K1Point, 
  ClpISecT283K1Curve, ClpSecT283K1Curve, ClpSecP256R1Field, 
  ClpISecP256R1FieldElement, ClpSecP256R1FieldElement, ClpISecP256R1Point, 
  ClpSecP256R1Point, ClpISecP256R1Curve, ClpSecP256R1Curve, 
  ClpBsiObjectIdentifiers, ClpEacObjectIdentifiers, ClpPlainDsaEncoding, 
  ClpStandardDsaEncoding, ClpIStandardDsaEncoding, ClpIPlainDsaEncoding, 
  ClpIDsaExt, ClpIDsaEncoding, ClpISchnorrDigestSigner, 
  ClpIECSchnorrSipaSigner, ClpECSchnorrSipaSigner, ClpSchnorrDigestSigner, 
  ClpPlainSchnorrEncoding, ClpIPlainSchnorrEncoding, ClpISchnorrEncoding, 
  ClpISchnorr, ClpISchnorrExt;

implementation

end.
